#!/usr/bin/env python3
"""bis-testgen: emit a pytest skeleton from a BIS spec.

For every objective, constraint, and edge case, one test function is generated with
the statement from the spec in its docstring and a NotImplemented body, so the test
suite exists (and fails) before any implementation is written. Constraints get a
Hypothesis property-test stub when hypothesis is installed.

Usage: bis-testgen.py SPEC.bis.yaml [-o tests/test_spec.py]
"""
import argparse, re, sys
try:
    import yaml
except ImportError:
    print("requires PyYAML"); sys.exit(2)

def ident(s):
    return re.sub(r"[^a-z0-9]+", "_", str(s).lower()).strip("_")[:60] or "x"

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("spec"); ap.add_argument("-o", "--out")
    a = ap.parse_args(); spec = yaml.safe_load(open(a.spec))
    L = ['"""Generated by bis-testgen from %s (%s). Fill the bodies; do not delete tests."""' % (a.spec, spec.get("id", "?")),
         "import pytest", "try:", "    from hypothesis import given, strategies as st", "    HAS_HYP = True",
         "except ImportError:", "    HAS_HYP = False", "", "SPEC_ID = %r" % spec.get("id", ""), ""]
    for i, o in enumerate(spec.get("objectives") or [], 1):
        L += ["def test_objective_%d_%s():" % (i, ident(o.get("objective"))),
              '    """O%d: %s — metric %s, target %s, hard floor %s."""' % (i, o.get("objective"), o.get("metric"), o.get("target"), o.get("hard_floor")),
              "    raise NotImplementedError('measure %s over the evaluation window and assert <= hard floor %s')" % (o.get("metric"), o.get("hard_floor")), ""]
    for c in spec.get("constraints") or []:
        cid = c.get("id", "C"); name = ident(c.get("rule"))
        L += ["@pytest.mark.skipif(not HAS_HYP, reason='hypothesis not installed')",
              "@given(st.data())",
              "def test_constraint_%s_%s(data):" % (cid, name),
              '    """%s: %s. Enforced at %s. Verified by %s."""' % (cid, c.get("rule"), c.get("enforced_at"), c.get("verified_by")),
              "    raise NotImplementedError('generate inputs with data.draw(...) and assert the invariant holds for all of them')", ""]
    for e in spec.get("edge_cases") or []:
        eid = e.get("id", "E")
        L += ["def test_edge_%s_%s():" % (eid, ident(e.get("condition"))),
              '    """%s: given %s, expected: %s."""' % (eid, e.get("condition"), e.get("expected")),
              "    raise NotImplementedError('arrange the condition, act, assert the expected behaviour')", ""]
    for t in spec.get("acceptance") or []:
        L += ["def test_acceptance_%s():" % ident(t.get("id")),
              '    """%s (%s) covers %s: %s"""' % (t.get("id"), t.get("type"), t.get("covers"), t.get("statement")),
              "    raise NotImplementedError()", ""]
    src = "\n".join(L)
    if a.out: open(a.out, "w").write(src); print("wrote", a.out, "(%d tests)" % src.count("\ndef test_"))
    else: print(src)

if __name__ == "__main__": main()
